server:
  servlet:
    context-path: /uaa
  port: 8999

spring:
  datasource:
    url: jdbc:h2:mem:library_test_db
    driverClassName: org.h2.Driver
    username: mike
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  flyway:
    enabled: false
  h2:
    console:
        enabled: true
        path: /h2

