server:
  port: 8999
spring:
  datasource:
    url: jdbc:h2:mem:auth_service_db
    driverClassName: org.h2.Driver
    username: mike
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
        enabled: true
        path: /h2
security:
      oauth2:
        client:
          clientId: 838651530957-qo25l1s5lljpd7hmeojrhljeq7r457h3.apps.googleusercontent.com
          clientSecret: xjhxIN4qDM6aLnCoPzhC7ocf
          accessTokenUri: https://www.googleapis.com/oauth2/v4/token
          userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
          clientAuthenticationScheme: form
          scope: openid,email,profile
      resource:
        userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
        preferTokenInfo: true